"""Container command builder for safe-whale.

All runs go through a Dockerfile: we generate one, write it to the data dir
(named by a content hash so Docker's layer cache does the heavy lifting), build
it once, then run with full security hardening on every invocation.
"""

from __future__ import annotations

import hashlib
import shlex
import shutil

from safe_whale.models import RunConfig

# ── Engine detection ──────────────────────────────────────────────────────────

SUPPORTED_ENGINES = ["docker", "podman", "nerdctl", "finch"]


def detect_engines() -> list[str]:
    """Return installed container engines in preference order."""
    return [e for e in SUPPORTED_ENGINES if shutil.which(e) is not None]


# ── Package name helpers ──────────────────────────────────────────────────────


def base_project(spec: str) -> str:
    """Extract the bare package name from a pip spec like 'httpie==3.2.2'."""
    s = spec.strip().split()[0] if spec.strip() else ""
    cut = len(s)
    for char in ("[", "<", ">", "=", "!", "~", "@"):
        idx = s.find(char)
        if 0 < idx < cut:
            cut = idx
    return s[:cut].strip()


# Keep old private name for tests that import it directly
_base_project = base_project


# ── Dockerfile generation ─────────────────────────────────────────────────────


def generate_dockerfile(cfg: RunConfig) -> str:
    """Generate a Dockerfile for the given RunConfig.

    Installs happen as root at build time so pip and apt have full write access.
    If non_root is set we create an unprivileged user and switch to it before
    the ENTRYPOINT, so --user and --read-only both work correctly at run time.
    """
    pkg = cfg.package_spec or "example"
    entry = cfg.entrypoint or base_project(pkg) or "python"
    apt = list(cfg.apt_packages)

    apt_step = ""
    if apt:
        apt_str = " ".join(apt)
        apt_step = f"""
RUN apt-get update \\
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends {apt_str} \\
 && rm -rf /var/lib/apt/lists/*
"""

    # --root-user-action=ignore silences the pip root warning; we want root
    # for the install so that site-packages is writable, then we drop privs.
    pip_flags = "--no-cache-dir --root-user-action=ignore"

    if cfg.non_root:
        user_step = """
RUN useradd -u 10001 -m appuser
USER appuser
WORKDIR /home/appuser
"""
    else:
        user_step = "\nWORKDIR /root\n"

    if cfg.interaction == "interactive":
        entrypoint_block = f'ENTRYPOINT ["{entry}"]'
    else:
        entrypoint_block = f'ENTRYPOINT ["{entry}"]\nCMD ["--help"]'

    return f"""# syntax=docker/dockerfile:1
# Generated by safe-whale — do not edit by hand.
FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1
{apt_step}
RUN pip install {pip_flags} "{pkg}"
{user_step}
{entrypoint_block}
"""


def image_tag(cfg: RunConfig) -> str:
    """Return a deterministic image tag derived from the Dockerfile content."""
    content = generate_dockerfile(cfg)
    digest = hashlib.sha1(content.encode(), usedforsecurity=False).hexdigest()[:12]
    safe_name = base_project(cfg.package_spec).replace("-", "_").lower() or "pkg"
    return f"safe-whale-{safe_name}-{digest}"


# ── Run argv builders ─────────────────────────────────────────────────────────


def build_run_argv(cfg: RunConfig, tag: str) -> list[str]:
    """Return the argv to `docker run` a pre-built image with full hardening."""
    parts = [cfg.engine, "run", "--rm"]

    if cfg.interaction == "interactive":
        parts.append("-it")
        # Curses / TUI apps need TERM set; containers don't inherit it from the host.
        parts += ["-e", "TERM=xterm-256color"]
    elif cfg.interaction == "pipe":
        parts.append("-i")

    if cfg.read_only:
        parts.append("--read-only")
    if cfg.limit_pids:
        parts += ["--pids-limit", "256"]
    parts += ["--memory", f"{cfg.memory_mb}m", "--cpus", str(cfg.cpus)]
    if cfg.no_new_privs:
        parts += ["--security-opt", "no-new-privileges"]
    if cfg.cap_drop_all:
        parts += ["--cap-drop", "ALL"]
    if cfg.non_root:
        parts += ["--user", "10001:10001"]
    if cfg.tmpfs_tmp:
        parts += [
            "--tmpfs",
            "/tmp:rw,nosuid,nodev,noexec,size=64m",
            "--tmpfs",
            "/var/tmp:rw,nosuid,nodev,noexec,size=64m",
        ]
    if cfg.block_network:
        parts += ["--network", "none"]
    if cfg.mount_dir:
        parts += ["-v", cfg.mount_dir]

    parts.append(tag)

    # The ENTRYPOINT is baked into the image; cli_args are forwarded to it.
    # This includes interactive/TUI apps, which still need their own argv.
    if cfg.cli_args:
        parts += shlex.split(cfg.cli_args)

    return parts


def build_display_command(cfg: RunConfig, tag: str) -> str:
    """Return a pretty multi-line shell string showing the run command."""
    command = _pretty_argv(build_run_argv(cfg, tag))
    if cfg.interaction == "pipe" and cfg.stdin_file:
        return f"{command} \\\n  < {shlex.quote(cfg.stdin_file)}"
    return command


def _pretty_argv(argv: list[str]) -> str:
    """Format an argv list as a readable multi-line shell command."""
    if not argv:
        return ""
    quoted = [shlex.quote(a) for a in argv]
    lines = [quoted[0] + " " + quoted[1]]  # "docker run"
    i = 2
    pair_flags = {
        "--memory",
        "--cpus",
        "--pids-limit",
        "--security-opt",
        "--cap-drop",
        "--user",
        "--network",
        "--tmpfs",
        "-v",
        "--build-arg",
        "-t",
        "-f",
        "-e",
    }
    while i < len(quoted):
        tok = quoted[i]
        if tok in pair_flags and i + 1 < len(quoted):
            lines.append(f"  {tok} {quoted[i + 1]}")
            i += 2
            continue
        lines.append(f"  {tok}")
        i += 1
    return " \\\n".join(lines)
